### ISSUE TITLE
Mail Cleaner does not work properly with controllers

### ISSUE THREAD

**Issue by Gvinfinity** [moraguma/GamutoWare#179]
- Possible explanation is that triggering the same input for a side in sequence bugs the handler

**Comment by moraguma** [comment]
I think switching this to action_just_pressed might just solve this! Also, maybe reducing the controller input deadzone

![image](https://github.com/moraguma/GamutoWare/assets/63124011/d4c8da78-1c0c-47a9-8305-d0a52093517b)

**Comment by Gvinfinity** [comment]
The `Input.is_action_just_pressed()` indeed solves it, according to the following documentation the used method returns true even if you already let the button go, as a way to prevent missed inputs. The more appropriate method solves the issue.
![image](https://github.com/moraguma/GamutoWare/assets/49999449/483560f9-fed1-47bb-8f9d-84355f9c944a)
