### ISSUE TITLE
Recorde Null

### ISSUE THREAD

**Issue by GoliasVictor** [moraguma/GamutoWare#68]
No itch.io o record não é salvo, fica null.

**Comment by moraguma** [comment]
Isso é por que na versão HTML não foi mandada com os dados de save. Eu não tenho certeza se ela é capaz de acessar os arquivos da mesma maneira, mas talvez incluir o arquivo de save na próxima build web resolva o problema. Caso ele não consiga acessar esse arquivo direito, a gente também pode codar um failsafe no caso de um arquivo de save nulo

Either way, o Godot 4 só deve ter capacidade de exportação web a partir da versão 4.1, então acho que só vale a pena se importar com isso a partir de lá

**Comment by GoliasVictor** [comment]
Fecha o problema quando ele tiver resolvido :D (e já lanço o godot 4.1)

**Comment by moraguma** [comment]
@GoliasVictor Valha eu fechei? Perdão

E ainda não lançou a versão estável não, acho que tu tá pensando no Godot 4.0.1

**Comment by IsaelGabriel** [comment]
A atualização do Godot resolveu este bug automaticamente. Logo sem necessidade de manter a Issue aberta.
